[STRICTDOC]
PROJECT_TITLE: MIL-STD-498 Requirements Documentation
PROJECT_VERSION: 1.0
PROJECT_ROOT: mil-std-498-strictdoc
OUTPUT_DIR: output/strictdoc

[STRICTDOC.OPTIONS]
ENABLE_MATH: True
ENABLE_CODE: True
ENABLE_TABLES: True
ENABLE_LINKS: True
ENABLE_META: True

[STRICTDOC.HTML]
HTML_STANDALONE: True
HTML_THEME: default
HTML_CSS_FILES: template/doorstop.css

[STRICTDOC.PDF]
PDF_STANDALONE: True
PDF_THEME: default

[STRICTDOC.MARKDOWN]
MARKDOWN_STANDALONE: True
MARKDOWN_THEME: default
