name: Doorstop MIL-STD-498 Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install pip as system executable
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo ln -sf /usr/bin/pip3 /usr/local/bin/pip
    
    - name: Install doorstop globally
      run: |
        pip install --upgrade pip
        pip install doorstop python-frontmatter
    
    - name: Convert requirements
      run: python3 convert_to_doorstop.py
    
    - name: Export documents
      run: |
        mkdir -p exports
        for doc in SRS SDD SSS IRS IDD SSDD SDP STP STD SPS SVD SUM CPM COM SCOM SIOM SIP FSM DBDD OCD STR STRP; do
          echo "Exporting $doc..."
          doorstop export $doc > exports/$doc.yaml
        done
    
    - name: Generate reports
      run: |
        mkdir -p reports
        echo "# MIL-STD-498 Requirements Summary Report" > reports/requirements_summary.md
        echo "Generated: $(date)" >> reports/requirements_summary.md
        echo "" >> reports/requirements_summary.md
        echo "## Document Requirements Count" >> reports/requirements_summary.md
        echo "" >> reports/requirements_summary.md
        for doc in SRS SDD SSS IRS IDD SSDD SDP STP STD SPS SVD SUM CPM COM SCOM SIOM SIP FSM DBDD OCD STR STRP; do
          count=$(find mil-std-498-doorstop/$doc -name "*.md" | wc -l)
          echo "- **$doc**: $count requirements" >> reports/requirements_summary.md
        done
        echo "" >> reports/requirements_summary.md
        echo "## Total Requirements: $(find mil-std-498-doorstop -name "*.md" | wc -l)" >> reports/requirements_summary.md
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: doorstop-outputs
        path: |
          exports/
          reports/
    
    - name: Create summary
      run: |
        echo "## Doorstop Documentation Generation Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Documents processed**: $(ls exports/*.yaml | wc -l)" >> $GITHUB_STEP_SUMMARY
        echo "- **Requirements converted**: $(find mil-std-498-doorstop -name "*.md" | wc -l)" >> $GITHUB_STEP_SUMMARY
        echo "- **Reports generated**: $(ls reports/*.md | wc -l)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Generated Files:" >> $GITHUB_STEP_SUMMARY
        echo "- YAML exports: \`exports/\`" >> $GITHUB_STEP_SUMMARY
        echo "- Reports: \`reports/\`" >> $GITHUB_STEP_SUMMARY 