# GitHub Actions workflow for publishing MIL-STD-498 documents to GitHub Pages
# Generated via Cursor IDE with AI assistance

name: Publish MIL-STD-498 Documents

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install doorstop python-frontmatter
        
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
        
    - name: Build project
      run: |
        make clean
        make all
        
    - name: Generate HTML files
      run: |
        # Create HTML files from markdown (since HTML publishing hangs)
        mkdir -p publications/html
        for doc in SRS SDD SSS IRS IDD SSDD SDP STP STD SPS SVD SUM CPM COM SCOM SIOM SIP FSM DBDD OCD STR STRP; do
          if [ -f "publications/markdown/$doc.md" ]; then
            echo "Converting $doc.md to HTML..."
            pandoc "publications/markdown/$doc.md" \
              --from markdown \
              --to html \
              --standalone \
              --css template/doorstop.css \
              --output "publications/html/$doc.html"
          fi
        done
        
    - name: Create index page
      run: |
        cat > publications/html/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>MIL-STD-498 Requirements Documentation</title>
            <link rel="stylesheet" href="../template/doorstop.css">
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .container { max-width: 1200px; margin: 0 auto; }
                .header { text-align: center; margin-bottom: 40px; }
                .section { margin-bottom: 30px; }
                .section h2 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
                .doc-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
                .doc-card { 
                    border: 1px solid #ddd; 
                    border-radius: 8px; 
                    padding: 20px; 
                    background: #f9f9f9;
                    transition: transform 0.2s;
                }
                .doc-card:hover { 
                    transform: translateY(-2px); 
                    box-shadow: 0 4px 8px rgba(0,0,0,0.1);
                }
                .doc-card h3 { margin-top: 0; color: #2c3e50; }
                .doc-card p { color: #666; margin-bottom: 15px; }
                .doc-link { 
                    display: inline-block; 
                    background: #3498db; 
                    color: white; 
                    padding: 8px 16px; 
                    text-decoration: none; 
                    border-radius: 4px;
                    transition: background 0.2s;
                }
                .doc-link:hover { background: #2980b9; }
                .category { margin-bottom: 40px; }
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>MIL-STD-498 Requirements Documentation</h1>
                    <p>Complete Software Development and Documentation Standards</p>
                    <p><em>Generated using Doorstop Requirements Management System</em></p>
                </div>
                
                <div class="category">
                    <h2>📋 Requirements Documents</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>Software Requirements Specification (SRS)</h3>
                            <p>Defines the functional and non-functional requirements for the software system.</p>
                            <a href="SRS.html" class="doc-link">View SRS</a>
                        </div>
                        <div class="doc-card">
                            <h3>System Specification (SSS)</h3>
                            <p>Describes the system-level requirements and constraints.</p>
                            <a href="SSS.html" class="doc-link">View SSS</a>
                        </div>
                        <div class="doc-card">
                            <h3>Interface Requirements Specification (IRS)</h3>
                            <p>Specifies requirements for system interfaces and data exchange.</p>
                            <a href="IRS.html" class="doc-link">View IRS</a>
                        </div>
                    </div>
                </div>
                
                <div class="category">
                    <h2>🏗️ Design Documents</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>Software Design Document (SDD)</h3>
                            <p>Describes the software architecture and detailed design.</p>
                            <a href="SDD.html" class="doc-link">View SDD</a>
                        </div>
                        <div class="doc-card">
                            <h3>System Design Document (SSDD)</h3>
                            <p>Defines the system architecture and high-level design.</p>
                            <a href="SSDD.html" class="doc-link">View SSDD</a>
                        </div>
                        <div class="doc-card">
                            <h3>Interface Design Document (IDD)</h3>
                            <p>Details the design of system interfaces and protocols.</p>
                            <a href="IDD.html" class="doc-link">View IDD</a>
                        </div>
                        <div class="doc-card">
                            <h3>Database Design Document (DBDD)</h3>
                            <p>Specifies database schema and data models.</p>
                            <a href="DBDD.html" class="doc-link">View DBDD</a>
                        </div>
                    </div>
                </div>
                
                <div class="category">
                    <h2>📋 Planning Documents</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>Software Development Plan (SDP)</h3>
                            <p>Outlines the development approach, schedule, and resources.</p>
                            <a href="SDP.html" class="doc-link">View SDP</a>
                        </div>
                        <div class="doc-card">
                            <h3>Software Test Plan (STP)</h3>
                            <p>Defines testing strategy, approach, and test procedures.</p>
                            <a href="STP.html" class="doc-link">View STP</a>
                        </div>
                        <div class="doc-card">
                            <h3>Software Installation Plan (SIP)</h3>
                            <p>Describes installation procedures and deployment strategy.</p>
                            <a href="SIP.html" class="doc-link">View SIP</a>
                        </div>
                        <div class="doc-card">
                            <h3>Software Transition Plan (STRP)</h3>
                            <p>Details the transition from development to operational use.</p>
                            <a href="STRP.html" class="doc-link">View STRP</a>
                        </div>
                    </div>
                </div>
                
                <div class="category">
                    <h2>🧪 Testing Documents</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>Software Test Description (STD)</h3>
                            <p>Provides detailed test cases and test procedures.</p>
                            <a href="STD.html" class="doc-link">View STD</a>
                        </div>
                        <div class="doc-card">
                            <h3>Software Test Report (STR)</h3>
                            <p>Documents test results and analysis.</p>
                            <a href="STR.html" class="doc-link">View STR</a>
                        </div>
                    </div>
                </div>
                
                <div class="category">
                    <h2>📦 Product Documents</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>Software Product Specification (SPS)</h3>
                            <p>Describes the software product and its components.</p>
                            <a href="SPS.html" class="doc-link">View SPS</a>
                        </div>
                        <div class="doc-card">
                            <h3>Software Version Description (SVD)</h3>
                            <p>Documents version information and release notes.</p>
                            <a href="SVD.html" class="doc-link">View SVD</a>
                        </div>
                    </div>
                </div>
                
                <div class="category">
                    <h2>📚 User Documentation</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>Software User Manual (SUM)</h3>
                            <p>Provides user instructions and operational procedures.</p>
                            <a href="SUM.html" class="doc-link">View SUM</a>
                        </div>
                        <div class="doc-card">
                            <h3>Computer Programming Manual (CPM)</h3>
                            <p>Contains programming interfaces and development guides.</p>
                            <a href="CPM.html" class="doc-link">View CPM</a>
                        </div>
                        <div class="doc-card">
                            <h3>Computer Operations Manual (COM)</h3>
                            <p>Describes computer operations and procedures.</p>
                            <a href="COM.html" class="doc-link">View COM</a>
                        </div>
                        <div class="doc-card">
                            <h3>Software Configuration Management Manual (SCOM)</h3>
                            <p>Details configuration management procedures.</p>
                            <a href="SCOM.html" class="doc-link">View SCOM</a>
                        </div>
                        <div class="doc-card">
                            <h3>Software Installation and Operations Manual (SIOM)</h3>
                            <p>Provides installation and operational procedures.</p>
                            <a href="SIOM.html" class="doc-link">View SIOM</a>
                        </div>
                        <div class="doc-card">
                            <h3>Operator Control Document (OCD)</h3>
                            <p>Describes operator controls and interfaces.</p>
                            <a href="OCD.html" class="doc-link">View OCD</a>
                        </div>
                        <div class="doc-card">
                            <h3>Firmware Support Manual (FSM)</h3>
                            <p>Contains firmware support and maintenance procedures.</p>
                            <a href="FSM.html" class="doc-link">View FSM</a>
                        </div>
                    </div>
                </div>
                
                <div class="category">
                    <h2>📊 Reports and Analysis</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>Requirements Summary</h3>
                            <p>Overview of all requirements across all documents.</p>
                            <a href="../reports/requirements_summary.md" class="doc-link">View Summary</a>
                        </div>
                        <div class="doc-card">
                            <h3>Traceability Matrix</h3>
                            <p>Requirements traceability and relationships.</p>
                            <a href="../reports/traceability_matrix.md" class="doc-link">View Matrix</a>
                        </div>
                        <div class="doc-card">
                            <h3>Coverage Report</h3>
                            <p>Requirements coverage analysis and metrics.</p>
                            <a href="../reports/coverage_report.md" class="doc-link">View Coverage</a>
                        </div>
                    </div>
                </div>
                
                <div class="category">
                    <h2>🔗 Quick Links</h2>
                    <div class="doc-grid">
                        <div class="doc-card">
                            <h3>All Documents (Markdown)</h3>
                            <p>Access all documents in Markdown format.</p>
                            <a href="../publications/markdown/" class="doc-link">Browse Markdown</a>
                        </div>
                        <div class="doc-card">
                            <h3>Project Repository</h3>
                            <p>View the source code and project structure.</p>
                            <a href="https://github.com/${{ github.repository }}" class="doc-link">View Repository</a>
                        </div>
                    </div>
                </div>
                
                <footer style="text-align: center; margin-top: 50px; padding: 20px; border-top: 1px solid #ddd; color: #666;">
                    <p>Generated on: <span id="generated-date"></span></p>
                    <p>MIL-STD-498 Requirements Documentation | Built with Doorstop</p>
                </footer>
            </div>
            
            <script>
                document.getElementById('generated-date').textContent = new Date().toLocaleDateString();
            </script>
        </body>
        </html>
        EOF
        
    - name: Copy template files
      run: |
        cp -r template publications/
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: publications

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 